apiVersion: v1
kind: Pod
metadata:
  name: dpdk-testpmd
  annotations:
    k8s.v1.cni.cncf.io/networks: [dpdk-net1, dpdk-net2]
  namespace: dpdk-net-ns
spec:
  restartPolicy: Never
  containers:
  - name: dpdk-testpmd
    image: quay.io/krister/centos8_nfv-container-dpdk-testpmd:latest
    imagePullPolicy: Always
    env:
    - name: PROMISC_DEVICES
      value: "n"
    - name: DISABLE_CPU_LOAD_BALANCE
      value: "n"
    - name: SRIOV_ID_A
      value: "SRIOV_VF_0"
    - name: SRIOV_ID_B
      value: "SRIOV_VF_1"
    - name: PCIDEVICE_OPENSHIFT_IO_SRIOV_VF_0
      value: "0000:86:0a.0"
    - name: PCIDEVICE_OPENSHIFT_IO_SRIOV_VF_1
      value: "0000:86:0a.1"
    - name: MTU
      value: "1500"
    securityContext:
      capabilities:
        add: ["IPC_LOCK","SYS_ADMIN"]
    resources:
      limits:
        cpu: 4
        memory: "1000Mi"
        hugepages-1Gi: "8Gi"
      requests:
        cpu: 4
        memory: "1000Mi"
        hugepages-1Gi: "8Gi"
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
  nodeSelector:
    node-role.kubernetes.io/master: ""
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
