apiVersion: v1
kind: Namespace
metadata:
    name: dpdk-net-ns
---    
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: dpdk-net-1
  namespace: openshift-sriov-network-operator
spec:
  ipam:  |
    {
    }
  networkNamespace: dpdk-net-ns
  resourceName: intel_dpdk_7f1
---  
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: dpdk-net-2
  namespace: openshift-sriov-network-operator
spec:
  ipam:  |
    {
    }
  networkNamespace: dpdk-net-ns
  resourceName: intel_dpdk_2f1
