#!/bin/bash

debug() {
  echo $@ >&2
}

usage() {
  echo Usage: $(basename $0) LABEL UNIT [envfile [varname]]
  echo
  echo Add additional labels to kubelet --node-labels command line option
  echo Extracts the contents of the first ExecStart stanza from the given systemd unit,
  echo   appends the LABEL to the --node-labels and returns the resulting string to STDOUT
  echo "If 'envfile' is provided, put it in there instead, as an environment variable named 'varname'"
  echo "Default 'varname' is EXECSTART if not specified"
  exit 1
}
LABEL=$1
UNIT=$2
ENVFILE=$3
VARNAME=$4
if [[ -z $UNIT || $UNIT == "--help" || $UNIT == "-h" ]]; then
  usage
fi
FILE=$(systemctl cat $UNIT | head -n 1)
FILE=${FILE#\# }
if [[ ! -f $FILE ]]; then
  debug "Failed to find root file for unit $UNIT ($FILE)"
  exit
fi
ORIG_EXECSTART=$(sed -n -e '/^ExecStart=.*\\$/,/[^\\]$/ { s/^ExecStart=//; p }' -e '/^ExecStart=.*[^\\]$/ { s/^ExecStart=//; p }' $FILE)
ORIG_EXECSTART=$(echo $ORIG_EXECSTART | sed 's/\\ //g')

ORIG_EXECSTART=${ORIG_EXECSTART#*kubelet}
RIGHT_SIDE=${ORIG_EXECSTART##*node-labels=}
OLD_LABELS=${RIGHT_SIDE%% *}
NEW_LABELS="$OLD_LABELS,$LABEL"
NEW_EXECSTART="${ORIG_EXECSTART/$OLD_LABELS/$NEW_LABELS}"
if [[ $ENVFILE ]]; then
  VARNAME=${VARNAME:-EXECSTART}
  echo "${VARNAME}=${NEW_EXECSTART}" > $ENVFILE
else
  echo $NEW_EXECSTART
fi
