kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: converter
rules:
- apiGroups:
  - ran.openshift.io
  - ""
  resources:
  - sites
  - configmaps
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
