apiVersion: v1
kind: Pod
metadata:
  name: presync
  namespace: default
spec:
  containers:
    - name: presync-container
      image: quay.io/vgrinber/presync:latest
      command:
      - /bin/bash
      - -c
      - "sleep inf"
  restartPolicy: Never