kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: converter
rules:
# Read Site resources
- apiGroups:
  - ran.openshift.io
  resources:
  - sites
  verbs:
  - get
  - watch
  - list

- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update


- apiGroups:
  - agent-install.openshift.io
  resources:
  - infraenvs
  - nmstateconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update


- apiGroups:
  - extensions.hive.openshift.io
  resources:
  - agentclusterinstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update


- apiGroups:
  - hive.openshift.io
  resources:
  - clusterdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update


- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update

