apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-sno
  namespace: assisted-installer
  labels:
    nmstate-label: cnfocto1-nmstate
spec:
  config:
    interfaces:
      - name: eno1
        type: ethernet
        state: up
        mac-address: E4:43:4B:F6:12:E0
        ipv4:
          enabled: true
          address:
            - ip: 10.16.231.11
              prefix-length: 24
            - ip: 10.16.231.43
              prefix-length: 24
            - ip: 10.16.231.44
              prefix-length: 24
          dhcp: false
    dns-resolver:
      config:
        server:
          - 10.19.42.41
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.16.231.254
          next-hop-interface: eno1
          table-id: 254
  interfaces:
    - name: eno1
      macAddress: E4:43:4B:F6:12:E0
