# permissions for end users to view sites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: site-viewer-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - sites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - sites/status
  verbs:
  - get
