FROM quay.io/openshift/origin-cli:latest

USER root

# For CLI use in pre-sync
RUN INSTALL_PKGS="jq" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y
    
# Create working directory
RUN mkdir /usr/src/hook &&\
    chown -R 1001:1001 /usr/src/hook        

WORKDIR /usr/src/hook

# For Python client
RUN python -m venv venv && \
    source venv/bin/activate && \
    python -m pip install --upgrade pip && \
    python -m pip install kubernetes
    

COPY --chown=1001 src/*  /usr/src/hook/
USER 1001
