apiVersion: v1
kind: Pod
metadata:
  name: ztp-site-generator
  namespace: ran-sites
spec:
  containers:
    - name: ztp-site-generator-container
      image: quay.io/redhat_emp1/ztp-site-generator:latest
      command:
      - /bin/bash
      - -c
      - "sleep inf"
  restartPolicy: Never